# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Andrew's coding notes
email: aspenceord@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Not a lot to say about my blog except that I will try and talk about
  the interesting things I am working on.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://aspenceord.github.io" # the base hostname & protocol for your site
twitter_username: aspenceord
github_username:  aspenceord

# Build settings
markdown: kramdown
